server:
  port: 7060

spring.application.name: rose-monitor
spring.profiles.active: dev

spring:
  cloud:
    nacos:
      username: nacos
      password: 123456
      discovery:
        server-addr: ${NACOS_HOST:rose-nacos}:${NACOS_PORT:8848}
        namespace: rose-${spring.profiles.active}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: rose-${spring.profiles.active}
  config:
    import:
      - optional:nacos:application.yaml
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yaml

canal:
  server:
    ip: localhost
    port: 11111
