spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:chensoul-mysql}:${MYSQL_PORT:3306}/chensoul-cloud?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password:

security:
  oauth2:
    client:
      client-id: chensoul-cloud
      client-secret: chensoul-cloud
      scope: server
