spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:chensoul-mysql}:${MYSQL_PORT:3306}/chensoul?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  activemq:
    broker-url: tcp://192.168.1.66:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 50

# 租户表维护
mybatis-plus:
  tenant:
    ignoreTables:
      - sys_client
      - sys_log
      - sys_tenant
      - sys_user
      - sys_credential

security:
  oauth2:
    client:
      client-id: chensoul-cloud
      client-secret: chensoul-cloud
      scope: server
    resource:
      jwt:
        key-value: chensoul-cloud
