spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:rose-mysql}:${MYSQL_PORT:3306}/rose?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

security:
  oauth2:
    client:
      client-id: rose
      client-secret: rose
      scope: server
