server:
  port: 9999

spring.application.name: chensoul-gateway
spring.profiles.active: dev

spring:
  cloud:
    nacos:
      username: nacos
      password: 123456
      discovery:
        server-addr: ${NACOS_HOST:chensoul-nacos}:${NACOS_PORT:8848}
        namespace: chensoul-${spring.profiles.active}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: chensoul-${spring.profiles.active}
        file-extension: yaml
  config:
    import:
      - optional:nacos:chensoul.yaml
      - optional:nacos:${spring.application.name}.yaml
